export default {
  courses: [],
  activities :[],
  course_schedule:[],
  selectedCourse :[],
  courseLecturer:[],
  courseTopics:[],
  coverage:[],
  courseTopicNumber:null,
  courseCoveredTopicNumber:null,
  courseNumberPerLecturer:null,
  userType:null,
  userDetails:[],
  courseDelegate:[],
  outline:[],
  NumOfCourseDelegate:null,
  attendCourse:[],
 /* course_delegate :[],
  coverage:[],
  courseTopicNumber:null,
  courseCoveredTopicNumber:null,
  courseLecturer:[],
  courseTopics:[],
  courseOfLecturer:[]*/
 
};
